name: Deploy Angular PWA

on:
  push:
    branches:
      - master  # Cambia a 'main' si ese es el nombre de tu rama

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build -- --configuration production --base-href /expense-tracker-pwa/

      - name: Inject Storage Configuration
        env:
          STORAGE_CONFIG: ${{ secrets.STORAGE_CONFIG }}
          API_URL: ${{ secrets.API_URL }}
          API_SECRET: ${{ secrets.API_SECRET }}
        run: node scripts/inject-storage-config.js

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/expense-tracker-pwa/browser # Ruta donde Angular deja el build
          branch: gh-pages # Rama donde se subirá el contenido estático
